test "ExprArmorStandProperties":
  spawn armor stand at location(11,11,11):

    assert small state of entity is false with "armor stand is not small"
    set small state of entity to true
    assert small state of entity is true with "armor stand is small"


    assert arms visibility state of entity is true with "armor stand has visible arms"
    assert arms invisibility state of entity is false with "armor stand doesn't have invisible arms"

    set arms visibility state of entity to false
    assert arms visibility state of entity is false with "armor stand doesn't have invisible arms"
    assert arms invisibility state of entity is true with "armor stand has invisible arms"

    set arms invisibility state of entity to false
    assert arms visibility state of entity is true with "armor stand has visible arms again"
    assert arms invisibility state of entity is false with "armor stand doesn't have invisible arms again"


    assert base plate visibility state of entity is true with "armor stand has visible base plate"
    assert base plate invisibility state of entity is false with "armor stand doesn't have invisible base plate"

    set base plate visibility state of entity to false
    assert base plate visibility state of entity is false with "armor stand doesn't have invisible base plate"
    assert base plate invisibility state of entity is true with "armor stand has invisible base plate"

    set base plate invisibility state of entity to false
    assert base plate visibility state of entity is true with "armor stand has visible base plate again"
    assert base plate invisibility state of entity is false with "armor stand doesn't have invisible base plate again"


    assert marker state of entity is false with "armor stand is not marker"
    set marker state of entity to true
    assert marker state of entity is true with "armor stand is marker"


    assert visibility state of entity is true with "armor stand is visible"
    assert invisibility state of entity is false with "armor stand isn't invisible"

    set visibility state of entity to false
    assert visibility state of entity is false with "armor stand isn't visible"
    assert invisibility state of entity is true with "armor stand is invisible"

    set invisibility state of entity to false
    assert visibility state of entity is true with "armor stand is visible again"
    assert invisibility state of entity is false with "armor stand isn't invisible again"


    assert tick state of entity is false with "armor stand can't tick"
    set tick state of entity to true
    assert tick state of entity is true with "armor stand can tick"


    assert move state of entity is false with "armor stand can't move"
    set move state of entity to true
    assert move state of entity is true with "armor stand can move"

    delete entity