test "ExprArmorStandHasBasePlate":
  spawn armor stand at location(0,0,0):
    assert base plate visibility state of entity is true with "base plate visibility state of armor stand %entity% is false instead of true"
    assert base plate invisibility state of entity is false with "base plate invisibility state of armor stand %entity% is true instead of false"

    set base plate visibility state of entity to false
    assert base plate visibility state of entity is false with "base plate visibility state of armor stand %entity% is true instead of false"
    assert base plate invisibility state of entity is true with "base plate invisibility state of armor stand %entity% is false instead of true"

    set base plate invisibility state of entity to true
    assert base plate visibility state of entity is false with "base plate visibility state of armor stand %entity% is true instead of false"
    assert base plate invisibility state of entity is true with "base plate invisibility state of armor stand %entity% is false instead of true"

    set base plate invisibility state of entity to false
    assert base plate visibility state of entity is true with "base plate visibility state of armor stand %entity% is false instead of true"
    assert base plate invisibility state of entity is false with "base plate invisibility state of armor stand %entity% is true instead of false"

    delete entity