test "ExprEntityEquipmentSlot":
  spawn zombie at location(10,100,10):
    set equipment chest slot of entity to iron chestplate
    assert equipment chest slot of entity is iron chestplate with "equipment chest slot of zombie %entity% is not iron chestplate"
    set entity's equipment chest slot and feet slot to dirt
    assert entity's equipment chest slot and feet slot are dirt with "equipment slots of zombie %entity% are not set to dirt"
    delete entity
