test "ExprBlockWaterLogged":
  set {_block} to block at location(0,0,0)
  set block at {_block} to oak planks
  assert waterlogged state of {_block} is false with "waterlogged state of %{_block}% is true instead of false"
  set waterlogged state of {_block} to true
  assert waterlogged state of {_block} is false with "waterlogged state of %{_block}% is true instead of false"
  set block at {_block} to oak trapdoor
  assert waterlogged state of {_block} is false with "waterlogged state of %{_block}% is true instead of false"
  set waterlogged state of {_block} to true
  assert waterlogged state of {_block} is true with "waterlogged state of %{_block}% is false instead of true"
