test "ExprEntityVariant":
  set {_loc} to location(7,7,7)
  parse if server version >= 1.20.5:
    spawn wolf at {_loc}:
      set {_variant} to woods
      set entity variant of entity to {_variant}
      assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
      delete entity
  parse if server version >= 1.21.2:
    spawn salmon at {_loc}:
      set {_variant} to small salmon variant
      set entity variant of entity to {_variant}
      assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
      delete entity
  parse if server version >= 1.19:
    spawn frog at {_loc}:
      set {_variant} to warm frog variant
      set entity variant of entity to {_variant}
      assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
      delete entity
  parse if server version >= 1.17:
    spawn axolotl at {_loc}:
      set {_variant} to blue axolotl variant
      set entity variant of entity to {_variant}
      assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
      delete entity
  set {_mushroom} to "mooshroom" parsed as entity type
  if {_mushroom} is not set:
    set {_mushroom} to mushroom cow
  spawn {_mushroom} at {_loc}:
    set {_variant} to brown mushroom cow variant
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn parrot at {_loc}:
    set {_variant} to blue parrot variant
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn llama at {_loc}:
    set {_variant} to creamy llama color
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn fox at {_loc}:
    set {_variant} to snow fox type
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn cat at {_loc}:
    set {_variant} to tabby
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn rabbit at {_loc}:
    set {_variant} to brown rabbit type
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn panda at {_loc}:
    set {_variant} to lazy
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity
  spawn tropical fish at {_loc}:
    set {_variant} to glitter tropical fish pattern
    set entity variant of entity to {_variant}
    assert entity variant of entity is {_variant} with "entity variant is %entity variant of entity% instead of %{_variant}%"
    delete entity

