test "ExprBlockWaterLogged":
  set {_block} to block at location(0,0,0)
  set block at {_block} to oak planks
  assert waterlogged state of {_block} is false with "oak planks isn't waterlogged"
  set waterlogged state of {_block} to true
  assert waterlogged state of {_block} is false with "oak planks can't be waterlogged"
  set block at {_block} to oak trapdoor
  assert waterlogged state of {_block} is false with "oak trapdoor isn't waterlogged"
  set waterlogged state of {_block} to true
  assert waterlogged state of {_block} is true with "oak trapdoor is waterlogged"