test "ExprEntityShouldBurnInDay" when the server is running paper:
  set {_location} to location(90,90,90)
  spawn phantom at {_location}:
    assert should burn during the day property of entity is true with "should burn during the day property of phantom %entity% is false instead of true"
    set should burn during the day of entity to false
    assert should burn during the day property of entity is false with "should burn during the day property of phantom %entity% is true instead of false"
    delete entity
  spawn skeleton at {_location}:
    assert should burn during the day property of entity is true with "should burn during the day property of skeleton %entity% is false instead of true"
    set should burn during the day of entity to false
    assert should burn during the day property of entity is false with "should burn during the day property of skeleton %entity% is true instead of false"
    delete entity
  spawn zombie at {_location}:
    assert should burn during the day property of entity is true with "should burn during the day property of zombie %entity% is false instead of true"
    set should burn during the day of entity to false
    assert should burn during the day property of entity is false with "should burn during the day property of zombie %entity% is true instead of false"
    delete entity
  stop if running minecraft "1.17"
  spawn stray at {_location}:
    assert should burn during the day property of entity is true with "should burn during the day property of stray %entity% is false instead of true"
    set should burn during the day of entity to false
    assert should burn during the day property of entity is false with "should burn during the day property of stray %entity% is true instead of false"
    delete entity