test "CondBoundingBoxOverlaps":
  set {_v::1} to vector(1,1,1)
  set {_v::2} to vector(2,2,2)
  set {_v::3} to vector(3,3,3)
  set {_b::1} to new bounding box from {_v::1} and {_v::2}
  set {_b::2} to new bounding box from {_v::1} and {_v::3}
  set {_b::3} to new bounding box from {_v::2} and {_v::3}
  assert {_b::1} overlaps {_b::2} with "bounding boxes overlap"
  assert {_b::1} doesn't overlap {_b::3} with "bounding boxes don't overlap"
